version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_auth
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis_container_auth
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "MyFakeRedisPass123"] # setting password
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
